#!/bin/bash

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       15
berryc top_gap            25

# Set decoration colors
berryc focus_color         292d3e
berryc unfocus_color       292d3e
berryc inner_focus_color   106060
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "courier-11"

# X hotkey deamon
sxhkd -c /home/henri/.config/berry/sxhkdrc &

# Bar
bash $HOME/.config/lemonbar/bar.sh &

# Compositor
compton &
